dist: xenial

language: c
cache:
  - ccache
  - pip
  - directories:
    - /opt/python

matrix:
  include:
    - os: linux
      env: PYENV_VERSION=3.6.4
    - os: linux
      env: PYENV_VERSION=3.7.0
    - os: linux
      env: PYENV_VERSION=3.8.0
    - os: linux
      env: PYENV_VERSION=pypy3.6-7.2.0

    - os: osx
      env: PYENV_VERSION=3.6.4
    - os: osx
      env: PYENV_VERSION=3.7.0
    - os: osx
      env: PYENV_VERSION=3.8.0
    - os: osx
      env: PYENV_VERSION=pypy3.6-7.2.0

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get update;
        sudo apt-get install liblo7 liblo-dev;
        pushd /opt/pyenv;
        git pull origin master;
        popd;
        sudo pip install pipenv;
      fi
  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        brew install liblo;
        pip install pipenv;
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
        ulimit -n 1200;
      fi

install:

  - cd $TRAVIS_BUILD_DIR
  - pyenv install $PYENV_VERSION --skip-existing;
  - pipenv install --python $(pyenv prefix $PYENV_VERSION)/bin/python --skip-lock;
  - pipenv run python setup.py install

script:
  - pipenv run python test.py