dist: xenial

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: ZtlduphZrPMDSA1wJPOH4MN03WmvV73mZF4gADmWcHEksNxeZYD744UqUa95pLnV6XGZgDxRNIls7ZcCjgNkkzvlDKRVdCAhrML0QvCn6YCQF5oH/hUjWhKy3mmvR6zcdYu/pGN0nYax2Ls8SmJo05MK4qAjIunJqoxbEfMS0EftqQzf4VDpUBNtvjn00k2IqNLM2pnAPa4BWFoQQTsgaXKzs4z2z2AjlR+7T08l3yXWTQahYITffb9O1dN5uXi2iKeR0ctgfonS26qgR3MyD4v56GUZGVX9PLYJMTYvJRBd3VaQ38vy7n3J6xCUeXGALOSb6+WcROcopoxE+m/5px9nVp28rc5C+bw6V2h3nzIYxRLZQV6pjGWV+t7p6vbnG772DZwsz1MWWtWEd2wmV18mS/h/rv6ZMiXYKdRI25v1WQgXzXn/vxDpZNnqWskrvBwrrEbnzrV3v6qR4rgYOaS+ihlCYSrh4tCvCWGodZ9A36LboC52mXqq1dSTBy+Di7C8vmCpy8sU9AdiRsT5cRdVvDEN7JQcTLHuwAZpy+2GYxULpGAF6do5PMzrJ0lGBic9MwxA1e++Bj1PoqXKjRgVYMyiPZ88oOj6dWei8axuTWqmZWpu8BLdnRAvdMnTf/VaNaPlYdpe8xgVmuQLzHDLlQu4Pb23djRtnSHX66s=
  on:
    tags: true

language: c
cache:
  - ccache
  - pip
  - directories:
    - /opt/python

matrix:
  include:
    - os: linux
      env: PYENV_VERSION=3.6.4
    - os: linux
      env: PYENV_VERSION=3.7.0
    - os: linux
      env: PYENV_VERSION=3.8.0
    - os: linux
      env: PYENV_VERSION=pypy3.6-7.2.0

    - os: osx
      env: PYENV_VERSION=3.6.4
    - os: osx
      env: PYENV_VERSION=3.7.0
    - os: osx
      env: PYENV_VERSION=3.8.0
    - os: osx
      env: PYENV_VERSION=pypy3.6-7.2.0

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get update;
        sudo apt-get install liblo7 liblo-dev;
        pushd /opt/pyenv;
        git pull origin master;
        popd;
        sudo pip install pipenv;
      fi
  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        brew install liblo;
        pip install pipenv;
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
        ulimit -n 1200;
      fi

install:

  - cd $TRAVIS_BUILD_DIR
  - pyenv install $PYENV_VERSION --skip-existing;
  - pipenv install --python $(pyenv prefix $PYENV_VERSION)/bin/python --skip-lock;
  - pipenv run python setup.py install

script:
  - pipenv run python test.py